SKPPL/DynamicPuzzle

package.json
=> fix : server.js production mode v2

components/PageElements/Modal/Tutorial.tsx
다시좀 리뷰해주세요 pull 받고 잘 작동되는지도 확인해주세요.
=> fixed : tutorial component fixed

components/PageElements/Particles/iceFlakeParticles.tsx
=> particles update

components/Game/Ceremony.tsx, components/Game/mypuzzle.tsx, components/Game/peerpuzzle.tsx, components/Game/styles.module.css, components/WebRTC/CheckReady.tsx, components/WebRTC/WebRTC.tsx, components/WebRTC/styles.module.css, pages/rooms/[roomName].tsx
ceremony update 및 ready update 적용
더 수정할 예정
=> ceremony ready UI update

components/Game/Ceremony.tsx, components/PageElements/PeerReady.tsx, components/WebRTC/CheckReady.tsx, components/WebRTC/WebRTC.tsx, components/WebRTC/styles.module.css, pages/rooms/[roomName].tsx
ceremony update
그리고 readystate에 따라서 표시되는 UI update
itembar 표시 업데이트 했습니다.
=> ceremony readystate update

components/PageElements/Modal/Tutorial.tsx
tutorial 게임 설명 영상 추가하였습니다.
초안으로 추후 계속 수정 예정입니다.
=> fixed : item tutorial description change video version

components/WebRTC/WebRTC.tsx, pages/api/webRTC/socket.tsx
webRTC 닉네임채널 제거, 카메라 오직 1개만 받도록 변경
null이름으로 된 방 목록에 안뜨게 수정하였ㅇ습니다.
=> fixed : web RTC null's room fix and code refectoring

components/Game/mypuzzle.tsx, components/Game/peerpuzzle.tsx, components/PageElements/Particles/myblackhallParticles.tsx, components/PageElements/Particles/myiceFlakeParticles.tsx, components/PageElements/Particles/mylipParticles.tsx, components/PageElements/Particles/myrocketParticles.tsx, components/PageElements/Particles/mytwirlParticles.tsx, components/PageElements/Particles/peerblackhallParticles.tsx, components/PageElements/Particles/peericeFlakeParticles.tsx, components/PageElements/Particles/peerlipParticles.tsx, components/PageElements/Particles/peerrocketParticles.tsx, components/PageElements/Particles/peertwirlParticles.tsx
particle을 수정했습니다.
일단 z-index 낮게 낮췄고 같이 나올 수 있게 파티클 분리했습니다.
=> particles fix

components/FaceDetection/FaceLandMarkMy.tsx, components/FaceDetection/FaceLandMarkPeer.tsx, components/FaceDetection/predictionMy.ts, components/FaceDetection/predictionPeer.ts
입술 좌표 및 반지름 연산시 모두 반올림처리 하여 정수로 바꾸었습니다.
=> fix: lip 좌표 소숫점 제거

components/Game/Segment.tsx, components/Game/SegmentState/defaultSegment.tsx, components/Game/mypuzzle.tsx, components/Game/peerpuzzle.tsx
상대가 맞췄을 때 해당 카드의 z-index 를 0으로 해주기 위해서 segment에 prop 추가했습니다.
=> peer isRightCard update, z-index fix

components/PageElements/Modal/Tutorial.tsx, components/WebRTC/RoomList.tsx, components/WebRTC/WebRTC.tsx, pages/api/webRTC/socket.tsx
아래 exception 핸들링 처리하였습니다.
카메라 미 허용 시 
1. 내가 방 만들 때
1. 정상적으로 카메라를 가져오지 못하였습니다. 대기실로 이동합니다. (방 미생성)
2. 내가 방 들어갈 때
1. 정상적으로 카메라를 가져오지 못하였습니다. 대기실로 이동합니다.
2. 호스트는 상대방이 떠났습니다. 새로운 게임을 즐기기 위해 방을 다시 만들어주세요. 알림 후 대기실로 이동
뒤로가기 
1. 내가 뒤로가기 할 경우
1. 나 : 뒤로가기를 눌러 방을 떠납니다. 현재 방은 종료됩니다
2. 상대방 : 상대방이 떠났습니다. 새로운 게임을 즐기기 위해 방을 다시 만들어주세요.
2. 상대방이 뒤로가기 할 경우 
위와 동일(반대)
새로고침
1. 내가 새로고침 할 경우 
1. 나 : 비정상적으로 방을 생성하였습니다. 방을 종료합니다.
2. 상대방 : 상대방이 떠났습니다. 새로운 게임을 즐기기 위해 방을 다시 만들어주세요.
2. 상대방이 새로 고침 할 경우 
위와 동일(반대)
탭닫기
1. 내가 탭 닫을 경우 
1. 나 : 비정상적으로 방을 생성하였습니다. 방을 종료합니다.
2. 상대방 : 상대방이 떠났습니다. 새로운 게임을 즐기기 위해 방을 다시 만들어주세요.
2. 상대방이 탭 닫을 경우 
위와 동일(반대)
=> fixed : web RTC room exception handling (backspace reload etc .. )

pages/api/webRTC/socket.tsx
=> fixed : web RTC room exception handling (backspace reload etc .. )_v3

components/Game/Segment.tsx, components/Game/SegmentState/defaultSegment.tsx, components/Game/SegmentState/ice.tsx, components/Game/SegmentState/magnet.tsx, components/Game/SegmentState/rocket.tsx, components/Game/atom.ts, components/Game/mypuzzle.tsx, components/WebRTC/CheckReady.tsx
myWait, peerWait true로 체크하는 것을 0 -> 9 로 체크하도록 변경하였습니다 코드리뷰 부탁드립니다.
=> fixed : segment state wait change (boolean to number)

components/Game/styles.module.css
=> start animation prevent drag

components/Game/SegmentState/defaultSegment.tsx, components/Game/store.tsx, components/Game/styles.module.css, components/WebRTC/CheckReady.tsx, components/WebRTC/styles.module.css, components/itemBar/DockCard/index.tsx
스타트애니매이션 변경하고 아이템바 크기랑 게임판 위치 수정했습니다.
=> start animation update and itembar gamepan UI update

components/Game/SegmentState/defaultSegment.tsx
=> gamepan update

components/Game/Segment.tsx, components/Game/SegmentState/defaultSegment.tsx, components/Game/SegmentState/ice.tsx, components/Game/mypuzzle.tsx
=> ice image bug fix

components/FaceDetection/FaceLandMarkMy.tsx, components/FaceDetection/FaceLandMarkPeer.tsx, components/PageElements/Loading.tsx, components/WebRTC/WebRTC.tsx
랜드마크 로딩을 위한 로딩 조건 추가하였습니다.
코드 리뷰 부탁드립니다.
=> feat : loading status add

components/WebRTC/WebRTC.tsx
모델 로드 후 나와 상대방 화면 간 컴포넌트 전환 차이 있던 부분 수정하였습니다.
=> Jeonje loading fix

components/Game/SegmentState/defaultSegment.tsx, components/Game/mypuzzle.tsx, components/Game/store.tsx, components/WebRTC/CheckReady.tsx, components/WebRTC/styles.module.css
적과 나의 퍼즐이 이제 다른 랜덤한 순서대로 배열되고 그 순서가 화면에 제대로 반영됩니다.
=> peer and my puzzles are differently ordered card

components/Game/SegmentState/defaultSegment.tsx
아이스 캔버스 중첩문제, 아이스 맞춘거는 안 얼게 했읍니다.
=> ice bug fix
